### ISSUE TITLE
Teambuild speicherung des Team-Titel

### ISSUE THREAD

**Issue by juschaefer** [ccmjs/akless-components#3]
Derzeit werden die Teambezeichnungen nicht in den Store aufgenommen. Falls andere Komponenten die Daten zu einem Team haben möchte, ist der Name derzeit nicht abfragbar.

**Comment by akless** [comment]
Im Datensatz eines Teams ist doch aber der Teamname als `name` enthalten?
Oder ist etwas anderes gemeint?

Beispiel:
```
{
  "name":"Gruppe 1",
  "members": {
    "rbrown2s": true,
    "sunger2s": true,
    "mkohl2s": true
  }
},
{
  "name": "Gruppe 2",
  "members": {
    "jkirsch2s":true,
    "mpapst2s":true,
    "rkeller2s":true
  }
}
```

**Comment by juschaefer** [comment]
Bei mir werden Datensätze der folgenden Art erstellt:

```json
{
    "_id" : "sose_19",
    "teams" : [ 
        {
            "key" : "1548600639880X5269760768997986",
            "members" : {
                "abc" : true
            }
        }, 
        {
            "key" : "1548601941683X14679065888073906",
            "members" : {
                "def" : true,
                "ghi" : true
            }
        }, 
        {
            "key" : "1548602385020X41594057288000386",
            "members" : {
                "jkl" : true
            }
        }
    ],
    "updated_at" : "2019-01-27T15:31:43+00:00"
}
```

Daraus kann ich derzeit keinen Titel ableiten.

**Comment by akless** [comment]
Hab nochmal genau nachgeschaut. Der Teamname ist unter der Property `name` vom Teamdatensatz. Wenn das Team noch keinen Namen hat, wird ein Standard-Teamname genommen (Team 1, Team 2, usw.). Man kann über `config.names` auch initiale Teamnamen vergeben. Wenn jemand einem Team beitritt, kann er den Teamnamen ändern. Schau im Zweifelsfall in den Code der `ccm.teambuild.js` oder spiele mal im Digital Maker Space bei der `Teambuild` unter `Create App` mal ein bißchen mit der Eingabemaske und der Vorschau rum.

**Comment by akless** [comment]
Habe eben ccm.teambuild.js v3.1.0 veröffentlicht. Da hat jetzt jeder Team-Datensatz immer einen Teamnamen.
