### ISSUE TITLE
helper-function formData -> exclude disabled input

### ISSUE THREAD

**Issue by mnutze** [ccmjs/akless-components#5]
sometimes reading disabled input fields isn't desired. so it could be a nice feature to toggle formData mode:
**1)** reading all input fields
**2)** reading enabled input fields only

suggestion:
```javascript
export function formData( element, enabledOnly ) {
  const ccm = framework( arguments );

  const data = {};
  const selector = enabledOnly ? '[name]:enabled' : [name]
  element.querySelectorAll( selector ).forEach( input => {
    ...
```

**Comment by akless** [comment]
Thanks for this enhancement! I have implemented it in [https://ccmjs.github.io/akless-components/modules/versions/helper-4.2.1.mjs](https://ccmjs.github.io/akless-components/modules/versions/helper-4.2.1.mjs). See also updated API here: [https://ccmjs.github.io/akless-components/api/ModuleHelper.InputElements.html#.exports.formData](https://ccmjs.github.io/akless-components/api/ModuleHelper.InputElements.html#.exports.formData).
