### ISSUE TITLE
Bürgervotum_ selection of next question 

### ISSUE THREAD

**Issue by flowingpsych** [ccmjs/akless-components#6]
Statt zufällig nächste Frage zu wählen, Algorithmus anpassen zu:
z.B. Frage mit meisten "wichtig"-Bewertungen zuerst und dann absteigend, bis alle beantwortet, dann "Alle Fragen beantwortet. Stelle selbst eine." oder so ähnlich ?!

https://github.com/ccmjs/akless-components/blob/master/quick_question/ccm.quick_question.js#L79

**Comment by akless** [comment]
Now the most liked questions come first. Questions with the same number of likes are coming in random order. After all questions are answered, the app starts with the most liked questions again.
